const Map<String, String> en = {
  'splash_slogan': 'set alarm and wake up easily',
  'splash_next': 'next',
  'alarm_hello': 'hello there!',
  'alarm_add': "let's add time sleep",
  'alarm_add_btn': 'add time sleep',
  'alarm_mo': 'mo',
  'alarm_tu': 'tu',
  'alarm_we': 'we',
  'alarm_th': 'th',
  'alarm_fr': 'fr',
  'alarm_sa': 'sa',
  'alarm_su': 'su',
  'alarm_voice': 'voice',
  'alarm_voice_men': 'man',
  'alarm_voice_woman': 'woman',
  'alarm_voice_robot': 'robot',
  'alarm_voice_ghost': 'ghost',
  'alarm_voice_create': 'create',
  'alarm_setting_sleep_time': 'setting sleep time',
  'alarm_setting_to_bed': 'to bed',
  'alarm_setting_wake_up': 'wake up',
  'alarm_setting_hours_of_sleep': ' hours of sleep',
  'snack_bar_announce': 'announce',
  'snack_bar_validate_alarm': 'choose date and alarm tone',
  'title_banner': 'you did it! here you can manage your alarm, change time and other things',
  'show_alarm_title': 'alarm',
};
