const Map<String, String> en = {
  'splash_slogan': 'set alarm and wake up easily',
  'splash_next': 'next',
  'alarm_hello': 'hello there!',
  'alarm_add': "let's add an alarm",
  'alarm_add_btn': 'add alarm',
  'alarm_mo': 'mo',
  'alarm_tu': 'tu',
  'alarm_we': 'we',
  'alarm_th': 'th',
  'alarm_fr': 'fr',
  'alarm_sa': 'sa',
  'alarm_su': 'su',
  'alarm_voice': 'voice',
  'alarm_voice_men': 'man',
  'alarm_voice_woman': 'woman',
  'alarm_voice_robot': 'robot',
  'alarm_voice_ghost': 'ghost',
  'alarm_voice_create': 'create',
};
