const Map<String, String> vi = {
  'splash_slogan' : 'đặt báo thức và thức dậy dễ dàng',
  'splash_next': 'tiếp tục',
  'alarm_hello': 'xin chào!',
  'alarm_add': "hãy thêm báo thức",
  'alarm_add_btn': 'thêm báo thức',
  'alarm_mo': 't2',
  'alarm_tu': 't3',
  'alarm_we': 't4',
  'alarm_th': 't5',
  'alarm_fr': 't6',
  'alarm_sa': 't7',
  'alarm_su': 'cn',
  'alarm_voice': 'giọng',
  'alarm_voice_men': 'nam',
  'alarm_voice_woman': 'nữ',
  'alarm_voice_robot': 'robot',
  'alarm_voice_ghost': 'ma',
  'alarm_voice_create': 'tạo',
};
