const Map<String, String> vi = {
  'splash_slogan' : 'đặt báo thức và thức dậy dễ dàng',
  'splash_next': 'tiếp tục',
  'alarm_hello': 'xin chào!',
  'alarm_add': "hãy thêm giờ ngủ",
  'alarm_add_btn': 'thêm giờ ngủ',
  'alarm_mo': 't2',
  'alarm_tu': 't3',
  'alarm_we': 't4',
  'alarm_th': 't5',
  'alarm_fr': 't6',
  'alarm_sa': 't7',
  'alarm_su': 'cn',
  'alarm_voice': 'giọng',
  'alarm_voice_men': 'nam',
  'alarm_voice_woman': 'nữ',
  'alarm_voice_robot': 'robot',
  'alarm_voice_ghost': 'ma',
  'alarm_voice_create': 'tạo',
  'alarm_setting_sleep_time': 'thiết lập thời gian ngủ',
  'alarm_setting_to_bed': 'đi ngủ',
  'alarm_setting_wake_up': 'thức dậy',
  'alarm_setting_hours_of_sleep': ' giờ ngủ',
};
